# Generated by Django 2.0.6 on 2020-04-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=20)),
                ('salt', models.CharField(max_length=36)),
                ('activation', models.BooleanField()),
            ],
            options={
                'db_table': 'cms_users_table',
                'managed': False,
            },
        ),
    ]
