# Generated by Django 2.0.6 on 2020-04-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cms_category_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cms_curriculum_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EssayTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('submit_time', models.DateTimeField()),
                ('content', models.TextField()),
                ('amount_of_reading', models.IntegerField()),
            ],
            options={
                'db_table': 'cms_essay_table',
                'managed': False,
            },
        ),
    ]
